name: Continuous Deployment

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Install dependencies
      run: |
        pip install pytest

    - name: Run Tests
      run: pytest # Adjust this based on how you run tests in your project

    - name: Deploy to VPS

      run: |
        ssh -i root@159.89.17.77 'cd /home/sillyGames && git pull'
        ssh -i root@159.89.17.77 'systemctl restart sillyGames'
